name = "petrogas-procurement"
compatibility_date = "2024-09-23"
main = "worker.js"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "petrogas-procurement-db"
database_id = "b6f44467-d4c6-421c-8a96-d3613ea518f2"
